---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "34.4.1"
      sourceRef:
        kind: HelmRepository
        name: traefik-repository
  values:
    deployment:
      replicas: 1
    service:
      type: NodePort
    ingressRoute:
      dashboard:
        enabled: true                               # Just to look what is it
