---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  chart:
    spec:
      chart: metrics-server
      version: "3.12.2"
      sourceRef:
        kind: HelmRepository
        name: metrics-server-repository
  values:
    args:
      - --kubelet-insecure-tls
      - --metric-resolution=15s
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    replicas: 2
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
    priorityClassName: system-cluster-critical
