---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
resources:
  - ../../apps/monitoring/
spec:
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      - kind: ConfigMap
        name: cluster_vars