---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
resources:
  - ../../apps/monitoring/
  #- ../../apps/ingress-nginx/

#TODO need to check crds of this guy: https://github.com/brainfair/awesome-flux-infra
