---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "8.11.3"
      sourceRef:
        kind: HelmRepository
        name: grafana-repository
  values:
    persistence:
      enabled: true
      size: 10Gi
    service:
      port: 3000
    admin:
      existingSecret: grafana-credentials
      userKey: adminUsername
      passwordKey: adminPassword
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: grafana.kube01.home.local
          paths:
            - path: /
              pathType: Prefix