---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "8.10.4"
      sourceRef:
        kind: HelmRepository
        name: grafana-repository
  values:
    persistence:
      enabled: true
      size: 10Gi
    service:
      port: 3000
    admin:
      existingSecret: grafana-credentials
      userKey: adminUsername
      passwordKey: adminPassword
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        traefik.ingress.kubernetes.io/router.middlewares: "default-replacepathregex@kubernetescrd"
      path: /grafana/?(.*)
      hosts:
        - kube01.home.local
