---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana-repository
  namespace: monitoring
spec:
  interval: 5m
  url: https://artifacthub.io/packages/helm/grafana/grafana